language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
env:
matrix:
  include:
    - rust: stable
      env: SYNTAX_CHECK=1
      install:
        - rustup component add rustfmt
      script:
        - cargo fmt -- --check

notifications:
    email: false
sudo: false
